- hosts: proxy
  become: yes
  roles:
    - common
    - proxy
    - firewall
  tags: proxy

- hosts: private
  become: yes
  roles:
    - private_proxy
    - firewall
    - apt
    - install_packages
  tags: private
