- hosts: proxy
  become: yes
  roles:
    - common
    - proxy
    - firewall
    - set_hostname
  tags: proxy

- hosts: private
  become: yes
  roles:
    - private_proxy
    - firewall
    - apt
    - install_packages
    - set_hostname
  tags: private
